### ISSUE TITLE
Demo (light) installation

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/istio#110]
**Description**
Provide a way to configure less resources for istio (like built-in demo profile). Resources should be configurable, but if configuration is not provided you can determine default based on cluster size.

**Reasons**
 I always get 3 ingress pods, 2 istiod, 2 cni. All of them require 512MB memory and significant CPU. In my small cluster with small traffic it doesn't make sense.

**Comment by pbochynski** [comment]
You can try how your operator works in the small cluster here: 
https://killercoda.com/kyma-project/scenario/modular-kyma
.
.
!!! Spoiler alert !!!!
.
.
.
It fails ;-)

**Comment by barchw** [comment]
PR: https://github.com/kyma-project/istio/pull/174
