### ISSUE TITLE
Change default CR name

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#132]
**Description**

The [name of the default CR](https://github.com/kyma-project/istio/blob/5a95e192b648b8a4d7bd632146819197cf87c4e5/config/samples/operator_v1alpha1_istio.yaml#L4) is set to `istio-sample`. In a recent Modularization meeting it was proposed to have the convention that the name the default CR should be `default`. There will also be a decision issue created for this.

ACs:
- [ ] The name of the default CR is updated to `default`
- [ ] All code and documentation referencing the old name `istio-sample` is updated

**Reasons**

To be consistent with the decision on the name for default CRs in modularization.

**DoD:**
- [ ] provide documentation

**Attachments**

**Comment by strekm** [comment]
already implemented
