### ISSUE TITLE
Istio operator integration test scenarios

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#137]
**Description**

Aggregated issue for Istio integration scenarios

- [ ] Follow-up issue for upgrade tests?

**Scenarios**

**in scope**: 
- [x] Test blocking strategy - uninstall with a created Custom Resource (e. g. Authorization Policy) and check that it fails 
-> delete the resource and check that uninstallation succeeds (in scope)
- [x] Verify that configuration from Istio CR is propagated to cluster state (in scope)
- [x] Verify that sidecars are removed after Istio is uninstalled (in scope) 
- [ ] Reconciliation should restart sidecars that don't match the expected version (in scope) -> Implement as upgrade test
  - I think this is out of scope since this would be better implemented as an upgrade test that runs continuously and verifies that a proxy deployed with the old version matches the Istio version after the upgrade. We also have this somehow implemented as part of the proxy reset tests. We need to think about how we want to handle upgrade tests since this requires deploying the last and latest version of the controller. A possible scenario could look like this:
  ```
    # TODO: We should replace the given version (e.g. "v20230605-b84290e2") with fetching the latest released version once we have this info available on GitHub
  Scenario: Upgrade from last to latest version
    Given "Istio CR" is not present on cluster
    And Istio CRD is installed
    And "Deployment" "istio-controller-manager" in namespace "kyma-system" with version "v20230605-b84290e2" is ready
    And Istio CR "istio-sample" is applied in namespace "default"
    And Istio CR "istio-sample" in namespace "default" has status "Ready"
    And Istio injection is enabled in namespace "default"
    And Application "test-app" is running in namespace "default"
    And Application pod "test-app" in namespace "default" has Istio proxy "present"
    When "Deployment" "istio-controller-manager" in namespace "kyma-system" with version "latest" is ready
    Then Istio CR "istio-sample" in namespace "default" has status "Ready"
    And Application "test-app" in namespace "default" has proxy in version "latest"
    And Istio resource "istiod" in namespace "istio-system" has version "latest" is ready
    And Istio resource "istio-ingressgateway" in namespace "istio-system" has version "latest" is ready
    And Istio resource "istio-cni-node" in namespace "istio-system" has version "latest" is ready
  ```
  
**out of scope**: 
- [ ] Reconciliation without changes in IstioCR should not update IstioCR status (out of scope)
  - I think this is something that is hard to verify reliable from the "outisde view" on the resource. I think it might be better to implement this as a unit test of the controller or as a envtest-based test.

Tests that require a different controller due to different Istio version:
- Version tests are already very well covered on Istio installation package tests. Also this tests are hard to implement in our current integration tests, since this would mean we need to deploy a specific version of the controller that needs to be built and available with a specific Istio version. I think this setup and environment is too complex for this kind of integration test. 

- [ ] Upgrade Istio to higher minor version should succeed (out of scope)
- [ ] Upgrade Istio to higher major version should fail (out of scope)
- [ ] Downgrade Istio version should fail (out of scope)

**PR**
- [x] https://github.com/kyma-project/istio/pull/167

**Comment by triffer** [comment]
Three of the 4 in scope tests were implemented. Comments were added for the other tests, since some of them might not be relevant. The 4th test that is in scope and was not implemented should be better covered as upgrade test. Since we want to discuss it and estimate this I'D propose to create a follow up issue for this.
