### ISSUE TITLE
Simplify Istio CR change checking

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#150]
**Description**
Istio Operator uses IstioCRChange abstraction that holds information about what happened since last reconciliation of Istio CR. The states that IstioCRChange hold are largely redundant. We should simplify the structure and use a bool instead of int. 

**Reasons**
Keeping code clean

**DoD:**
~~- [ ] provide documentation~~
~~- [ ] release notes and What's New updates for Kyma customers~~
- [ ] provide unit tests
~~- [ ] provide integration tests~~
- [ ] test on production-like environment
~~- [ ] verify resource limits~~
~~- [ ] followup issue~~

**Comment by werdes72** [comment]
Done in https://github.com/kyma-project/istio/issues/181
