### ISSUE TITLE
Restart injected pods after Proxy configuration changes in Istio CR

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#152]
**Description**
After the config for proxy changes, the controller should restart Pods for the configuration to be up to date.

AC:
- [x] Restart proxy after proxy resource configuration changed in Istio CR
- [x] Restart proxy after proxy resource configuration in default IstioOperator template changed

**DoD:**
- [x] provide documentation
~~- [ ] release notes and What's New updates for Kyma customers~~
- [x] provide unit tests
- [x] provide integration tests
- [x] test on production-like environment
- [x] verify resource limits
- [x] followup issue
  - https://github.com/kyma-project/istio/issues/157  
  - https://github.com/kyma-project/istio/issues/161

**PR**
- https://github.com/kyma-project/istio/pull/160

**Attachments**
- https://github.com/kyma-project/istio/issues/143

**Comment by triffer** [comment]
Documentation was added to documentation issue: https://github.com/kyma-project/istio/issues/146#issuecomment-1573387907
