### ISSUE TITLE
Update Technical design documentation

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#188]
The technical design was not adjusted after the implementation started. During the implementation we have gained new knowledge and therefore the documentation is probably no longer correct. 
Furthermore, we should think about whether we can restructure the documentation.

PR:
- https://github.com/kyma-project/istio/pull/495

Follow-up issue:
- https://github.com/kyma-project/istio/issues/499

**Comment by nataliasitko** [comment]
The xff-proposal document is not up-to-date and the Istio CR example it includes is incomplete. Therefore, as part of this issue, it should also be reviewed and updated.
