### ISSUE TITLE
Istio module Grafana monitoring dashboard

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#242]
**Description**
Configure KCP VictoriaMetrics to collect Istio CR status metrics and create a Grafana dashboard for monitoring.

**Reasons**
Production ready Istio

**DoD:**
- [x] provide documentation
- [x] test on skr

**Attachments**

https://github.com/orgs/kyma-project/projects/27/views/1?filterQuery=ready%3ASprint+sprint-number%3A114+assignee%3Abarchw&pane=issue&itemId=32866765

BTP Operator (Stage Grafana):
https://grafana.cp.stage.kyma.cloud.sap/d/4pfTYUlVz/modules-btp-manager

Istio dashboard (Stage Grafana):
https://grafana.cp.stage.kyma.cloud.sap/d/hTm72lVIz/modules-istio

Useful:
https://play.grafana.org/dashboards

**Open questions:**
* reconciler/controller metrics?
* alerts?

**Comment by videlov** [comment]
![Image](https://github.com/kyma-project/istio/assets/10164673/764213d1-4eb7-47f6-995c-b784460438d6)

**Comment by videlov** [comment]
![Image](https://github.com/kyma-project/istio/assets/10164673/d86247bf-7f31-4f2c-8072-f47eab8f7d72)
