### ISSUE TITLE
Support of annotation for istio-ingressgateway

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/istio#40]
**Description**
We want to enable possibility to set additional annotations for istio-ingressgateway, to be able to override default configuration created by cloud-providers.

**Reasons**
AWS NLB created by the K8S AWS cloud-provider controller works in "hybrid" TCP reverse proxy mode: it terminates TCP connections and reverse proxies them to the backends, however all frames beyond TCP are bypassing the LB, i.e. TLS is terminated by the istio-ingressgateway.
By default the K8S cloud provider configured the NLB with 60 seconds idle timeout on downstream connections, so it was terminating TCP connections from the client if lasting more than 60 seconds and not sending keepalives.
This causes that long running queries - longer then 60s - are dropped.

Right now applying the _service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"_ annotation on the ingressgateway is the only way to decide how long queries workload wants to support.

**DoD:**
- [ ] provide documentation
- [ ] provide unit tests
- [ ] test on SKR
- [ ] verify resource limits
- [ ] followup issue
- [ ] publish release notes and _What's New_ updates for Kyma customers
- [ ] verify resource limits
- [ ] followup issue

**Attachments**
[AWS Application Load Balancers: Load balancer attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes)

**Comment by strekm** [comment]
this will be implemented in api-gateway module
