### ISSUE TITLE
Bump Istio to 1.19.3

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#417]
**Description**

Bump Istio libs and components to version 1.19.3

ACs:
- [x] istio running on 1.19.3 version
- [x] sidecars are running on 1.19.3 version
- [x] verify zero downtime during istio upgrade following the process described in https://github.com/kyma-project/istio/issues/429
- [x] update grafana dashboards if needed
- [x] new image available in Kyma external repository
- [x] istio released and bumped in kyma
- [x] gardener cluster can be hibernated
- [x] run smoke test (expose httpbin with sidecar)
- [x] run manual tests

**Reasons**

Keeping Istio up to date

**DoD:**
~~- [ ] Create a follow-up issue.~~
~~- [ ] Provide unit tests.~~
~~- [ ] Provide integration tests.~~
~~- [ ] Provide documentation.~~
- [x] Test on a production-like environment.
- [x] Check the outcome of all related pipelines.
~~- [ ] Verify resource limits.~~
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
- [x] Create a release and bump in Kyma.
- [x] Add release notes and What's New notes for Kyma customers.

**Attachments**
https://istio.io/latest/news/releases/1.19.x/announcing-1.19.3/
PRs to Kyma repo: 
- https://github.com/kyma-project/kyma/pull/18349
- https://github.com/kyma-project/kyma/pull/18350

**Comment by werdes72** [comment]
Zero downtime upgrade test is in separate issue: https://github.com/kyma-project/istio/issues/429
