### ISSUE TITLE
Public AWS Load Balancer IP not available in XFF header

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#420]
**Description**

The public IP address of an AWS load balancer is not in the XFF header. The XFF header only contains the private address of the load balancer. The external IP address of the load balancer (e.g. `ac4d7ac87e3c84421aafb5452b295c2a
1646890990.eu-central-1.elb.amazonaws.com`), resolves to three IP addresses. 

In the [AWS Proxy Protocol documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html#proxy-protocol), it is mentioned that “The address of the proxy in the header for IPv6 is the public IPv6 address of your load balancer. This IPv6 address matches the IP address that is resolved from your load balancer's DNS name, which begins with either ipv6 or dualstack. If the client connects with IPv4, the address of the proxy in the header is the private IPv4 address of the load balancer, which is not resolvable through a DNS lookup.”. It looks like it’s a limitation that it’s not possible to get the external IP of the Load Balancer when using IPv4. This is only possible when the client connects via IPv6.

**Reasons**
With this behaviour it is hard to get the complete chain of public IPs in a request.
@fabiovarisco contacted us, because they have a requirement to know exactly which IP address the client used to connect to the load balancer.

We should investigate if there is any option to supply the expected IP in the XFF header.

**DoD:**
- [ ] Create a follow-up issue.
- [ ] Provide unit tests.
- [ ] Provide integration tests.
- [ ] Provide documentation.
- [ ] Test on a production-like environment.
- [ ] Check the outcome of all related pipelines.
- [ ] Verify resource limits.
- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
- [ ] Create a release and bump in Kyma.
- [ ] Add release notes and What's New notes for Kyma customers.

**Attachments**

**Comment by fabiovarisco** [comment]
Hello colleagues, 

Do you have any updates on this? Any ideas on where to look to get the complete chain of public IPs in a request?

Best regards,
Fabio

**Comment by strekm** [comment]
hello @fabiovarisco, 
we did not have time yet to look into this issue. i will keep you updated but i need to admit that atm it is not our highest priority.

Cheers, 
Magda

**Comment by tlalexandri** [comment]
Hello Colleagues, 

This topic would be very critical for us, due to the legal request from HMRC on Fraud Prevention Headers (Gov-Vendor-Forward header, 
https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/).

Could you please provide an estimation or planned date for its availability (as it is a legal requirement)? 
In case a call could be helpfull please just let us know to provide further details.

With best regards, 
Tiago

**Comment by triffer** [comment]
Hi @tlalexandri, @fabiovarisco,
we have looked into the topic and what we can do.

As far as I understand it, you need the public IP of the AWS LB, as this is the public IP of your service that is called by the client. This is probably also relevant for the `Gov-Vendor-Public-IP` header.  
Following our documentation about [TLS termination](https://github.com/kyma-project/istio/blob/main/docs/user/00-10-overview-istio-controller.md#tls-termination), this is done inside the service mesh. As far as I understand your request and the [HMRC documentation on Gov-Vendor-Forwarded](https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/#gov-vendor-forwarded), this public IP is still required even though AWS ELB does not perform TLS termination before the service mesh. The TLS termination is done on the private network within the Kubernetes cluster, but the AWS LB IP is the public representation of your service.

Unfortunately, due to technical limitations of AWS ELB in ipv4 mode, the public load balancer IP of the request is not available to the components in the service mesh and there is no way for us to work around this. The only information available is the hostname in the `istio-ingressgateway`service.
We also improved the [XFF-header documentation](https://github.com/kyma-project/istio/blob/main/docs/user/00-10-overview-istio-controller.md#x-forwarded-for-http-header) to make it clearer.

As this is a platform restriction, this [HMRC documentation about missing headers](https://developer.service.hmrc.gov.uk/guides/fraud-prevention/getting-it-right/#missing-header-data) might be applicable.

Regards,
Tim

**Comment by fabiovarisco** [comment]
Hello @triffer,

Thanks for checking this and for confirming the limitation.

Unfortunately, HMRC is not accepting our exemption requests. So we'll probably need to find a workaround for that. 

I have one additional question: in the [XFF-header documentation](https://github.com/kyma-project/istio/blob/main/docs/user/00-10-overview-istio-controller.md#x-forwarded-for-http-header), it says: 
> Due to [technical limitations of AWS Classic ELBs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html#proxy-protocol), when using an IPv4 connection, the header does not include the public IP of the load balancer in front of Istio Ingress Gateway. Moreover, Istio Ingress Gateway Envoy does not append the private IP address of the load balancer to the XFF header, effectively removing this information from the request.

So, I understand that the Proxy IP (from proxy protocol) is not included in the request at all. Does it work the same way for IPv4 and IPv6? Because the limitation on AWS LB is only related to IPv4. So, we are wondering if we could obtain the Load Balancer's IP when the client connects via IPv6? Is this information available in the request? 

Thanks,
Fabio

**Comment by triffer** [comment]
Hi @fabiovarisco
about your question:

> So, I understand that the Proxy IP (from proxy protocol) is not included in the request at all. Does it work the same way for IPv4 and IPv6? Because the limitation on AWS LB is only related to IPv4. So, we are wondering if we could obtain the Load Balancer's IP when the client connects via IPv6? Is this information available in the request?

As far as I could verify, the proxy protocol sent by the AWS LB has a client IP and proxy IP set. For some reason the proxy IP is removed by the Envoy proxy and I couldn't find the reason, yet. So I cannot say how it will behave with IPv6.
Also we don't support IPv6 with Kyma and our default Istio configuration, yet.
I tried to use IPv6 to see how it behaves, but I couldn't get it to work correctly. 

Regards,
Tim
