### ISSUE TITLE
Investigate validating webhook patching error

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#51]
**Description**
When running istio reconcilation the following error is happening:

> Failed to update validatingwebhookconfiguration istio-validator-istio-system (failurePolicy=Fail, resourceVersion=42575275): Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io "istio-validator-istio-system": the object has been modified; please apply your changes to the latest version and try again

The issue was meant to already be fixed on Istio site: https://github.com/istio/istio/issues/36478

**Expected result**
The error should not happen

**Steps to reproduce**
Running `kyma deploy --component istio` will cause the error to happen, but it is also possible to reproduce with `istioctl apply` with istiooperator rendered by reconciler.

**Comment by videlov** [comment]
solves: https://github.tools.sap/kyma/backlog/issues/3417

**Comment by videlov** [comment]
Issue is easily reproducible. There are couple of similar issues on Istio github, but not prioritised or fixed. Created a new one, explaining how to reproduce and what is the potential cause.

https://github.com/istio/istio/issues/42987

We can not do anything more on Kyma / Reconciler.
