### ISSUE TITLE
Consistent labeling

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#548]
**Description**

Based on [decision](https://github.com/kyma-project/community/issues/864) implement module labeling and common labeling for all resources managed by istio module.

ACs:
- [x] labels are aligned with module labeling
- [x] common labels implemented
- [x] it is possible to use label selector to filter module resources
- [x] Building image for release is adapted to use the new version build arg
- [x] UI resources are labeled
- [ ] Release notes for common labels are added
```
Introduce consistent labeling for the Kyma modules. For more information, see the [documentation](https://kyma-project.io/#/istio/user/00-10-overview-istio-controller?id=labeling-resources).
```

**Reasons**

Consistent labeling

**DoD:**
~~- [ ] Create a follow-up issue.~~
- [x] Provide unit tests.
~~- [ ] Provide integration tests.~~
- [x] Provide documentation.
~~- [ ] Test on a production-like environment.~~
~~- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.~~
- [x] Check the outcome of all related pipelines.
~~- [ ] Verify resource limits.~~
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
~~- [ ] Create a release.~~
~~- [ ] Add release notes and What's New notes for Kyma customers.~~

**Attachments**

**Comment by abbi-gaurav** [comment]
@strekm , please also take into account this comment: https://github.com/kyma-project/community/issues/864#issuecomment-1875068132

**Comment by Ressetkk** [comment]
Done!
/close
