### ISSUE TITLE
Istio 1.20.3 bump

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#567]
**Description**

Update Kyma Istio module to use Istio in version 1.20.3 Update Istio version and used dependencies, adjust tests and documentation if needed. Upgrade needs to be with zero downtime for production settings. 

ACs:
- [x] review Istio RNs
- [x] istio bumped on [main](https://github.com/kyma-project/istio/pull/620) and latest [release branch (release-1.3)](https://github.com/kyma-project/istio/pull/621)
- [x] prepare kyma istio RNs based on Istio RNs
- [x] istio installs and upgrades to 1.20.3 version
- [x] istio module upgrades with zero downtime - https://github.com/kyma-project/istio/issues/429
- [x] tests and documentation updated if needed
- [x] verify that sidecars are in sync with control-plane

**Reasons**

Keeping Istio up to date

**DoD:**
~~- [ ] Create a follow-up issue.~~
~~- [ ] Provide unit tests.~~
~~- [ ] Provide integration tests.~~
- [x] Provide documentation.
- [x] Test on a production-like environment.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] Check the outcome of all related pipelines.
~~- [ ] Verify resource limits.~~
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
~~- [ ] Create a release~~
- [x] Add release notes

**Attachments**
https://istio.io/latest/news/releases/1.20.x/announcing-1.20.2/
https://istio.io/latest/news/releases/1.20.x/announcing-1.20/upgrade-notes/

**PRs**
- https://github.com/kyma-project/istio/pull/620
- https://github.com/kyma-project/istio/pull/621

**Comment by videlov** [comment]
@howardjohn we actually tested 1.20.1 only with the commit I mention and it did break our k3d setup, however the fix resolves the issue, we also managed to validate it. thanks for fixing it so quickly. hope 1.20.3 is released soon.

**Comment by videlov** [comment]
Istio 1.20.3 is out - https://istio.io/latest/news/releases/1.20.x/announcing-1.20.3/
