### ISSUE TITLE
Telemetry CR in UI

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#579]
**Description**

Add UI extension for Telemetry CRD.

ACs:
- [x] it is possible to manage Telemetry CR using Kyma dashboard
- [x] UI is tested with automated test

**Reasons**

Improve UX of Istio module

**Attachments**
https://kyma-project.io/#/istio/user/operation-guides/02-30-enable-istio-access-logs
https://istio.io/latest/docs/reference/config/telemetry/
https://github.com/kyma-project/istio/tree/main/config/ui-extensions

**PR**
- https://github.com/kyma-project/istio/pull/758

**Comment by a-thaler** [comment]
I assume not all options should be supported in the form view as they are not part of any documented use case. We should select wisely and promote the settings important for our flows like the simple activation of access logs using the predefined provider (not any custom provider)
