### ISSUE TITLE
Istio operator integration test

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#58]
**Description**

Create a test for Install and Uninstall of Istio component

**Reasons**

Provide production ready Istio module

**DoD:**
- [x] Installation test
- [x] Uninstallation test
- [x] Test is running on pipeline in Prow (k3d)
- [ ] follow up task created
- [x] pipeline documented

**Attachments**

Development was started in https://github.com/kyma-project/istio/pull/57

**PR**
- https://github.com/kyma-project/istio/pull/133

**Comment by strekm** [comment]
use k3d cluster, testing operator, verify: pilot, gateway, cni is installed, CRDs installed, run istio verify
