### ISSUE TITLE
Enable TLS without termination in Gateway API

### ISSUE THREAD

**Issue by danail-branekov** [kyma-project/istio#580]
**Description**

In order to have a Gateway API gateway [without TLS termination](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/) in Istio, we need to set the `PILOT_ENABLE_ALPHA_GATEWAY_API` env var to `true` on the `istiod` deployment.

Currently there is no way to do this via the Kyma Istio Resource [Spec](https://github.com/kyma-project/istio/blob/11c032ec4f0d1d9178d747d7648ae0559fc0c222/api/v1alpha1/istio_types.go#L127-L132).

**Reasons**

This feature is requred by [Korifi](https://github.com/cloudfoundry/korifi) if it is to run on Kyma. Here is Korifi's [Gateway definition](https://github.com/cloudfoundry/korifi/blob/1e4b89dbe8eac25d43427c182052ffbbc0b5edc5/helm/korifi/templates/gateway.yaml#L41-L43)

**DoD:**
- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.

**Attachments**

**Comment by strekm** [comment]
closing in favour of https://github.com/kyma-project/istio/issues/669
