### ISSUE TITLE
Support different CNI configs

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/istio#61]
**Description**

Istio Operator should provide a possibility to configure Istio CNI, because different clusters have a different configurations.
This is an example difference between k3d and GCP cluster:
```bash
<       cniBinDir: /opt/cni/bin
<       cniConfDir: /etc/cni/net.d
---
>       cniBinDir: /bin
>       cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
```

**Reasons**

Istio Operator should support different types of clusters.

**DoD:**
- [ ] provide documentation
- [ ] test on SKR

**Comment by strekm** [comment]
closing cause of https://github.com/kyma-project/istio/issues/95
