### ISSUE TITLE
Improve documentation of Istio version

### ISSUE THREAD

**Issue by triffer** [kyma-project/istio#610]
**Description**

We should provide a better documentation about what Istio version will be installed by a specific release. We can do that by extending the release notes with the information about the bundled Istio version.
Additionally, we should document how users can get the Envoy version of this Istio version.

**Reasons**
Better documentation about Istio version provided by module.

**AC**
- [x] Release-notes generation in pipeline adds Istio and Envoy version during release
- [x] Istio module documentation is updated during istiop bump task to include the Istio and envoy version

**DoD:**
- [x] Provide documentation.

**Attachments**

- [Release created with version automation in fork repository](https://github.com/triffer/istio/releases/tag/1.7.0)
- https://github.com/kyma-project/istio/pull/847

**Comment by strekm** [comment]
- extend release notes generation to include Istio and Envoy version
- extend Istio main documentation

**Comment by triffer** [comment]
I checked the automation for updating the main README.md, but I think it's not worth the effort.
