### ISSUE TITLE
Allow configuration of XFCC forwarding like available for https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/#configuring-x-forwarded-client-cert-headers

### ISSUE THREAD

**Issue by Frank-Stephan** [kyma-project/istio#611]
**Description**
An external service that uses mtls calls an application running in a Kyma cluster. To be able to check the identity of the external 
 caller, the caller's certificate is needed. In istio forwardClientCertDetails can be configured to achieve this. In a SAP managed Kyma cluster this isn't supported. 

**Reasons**
An application must be able to check the subject of a client certificate of an external mtls client, to check its identity.  

**DoD:**
- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.

**Attachments**

**Comment by strekm** [comment]
hello, @Frank-Stephan can you please provide some details. Best would be to have some steps to reproduce. Default value for `forwardClientCertDetails` is `SANITIZE_SET`. As to my knowledge with this setting caller certificate should be there.

cheers, 
Magda
