### ISSUE TITLE
Sidecar image for reconcile should be taken from Istio Operator file

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#651]
**Description**

Sidecar image used for reconciliation should be taken from Istio Operator file instead of hardcoded value.

**Expected result**

Sidecar is reconciled using image from Istio Operator

**Actual result**

Sidecar is reconciled using hardcoded image

**Steps to reproduce**

Change image in Istio Operator and wait for Istio reconcile

**Troubleshooting**
https://github.com/kyma-project/istio/blob/269fa6d1cf6ac4785f70e45004cbac62a60c28f0/internal/reconciliations/proxy/sidecars.go#L48

**Comment by videlov** [comment]
**Background**
We do not use IstioOperator CR for Istio installation, this is a result from `istioctl install`.
Active configuration is used from `istiod` from ConfigMap `istio-system/istio-sidecar-injector`

Even if changed in the CM on our operator reconcile we replace it from its original value defined in here:
https://github.com/kyma-project/istio/blob/main/manifests/istio-operator-template.yaml#L146

**To fix**
Fix in this issue will be to get rid of constant variable in: 
https://github.com/kyma-project/istio/blob/main/internal/reconciliations/proxy/sidecars.go#L48

and reuse from operator template manifest YAML

**Workaround**
Using custom proxy image is possible for customers using: https://istio.io/latest/docs/reference/config/annotations/#SidecarProxyImage

**Consideration**
* If we want to offer custom images it has to be hosted by us (our hub), this will be tackled in another issue.
* We may also include `Warning` state of Istio CR if we detect customer is using `SidecarProxyImage` [annotation](https://istio.io/latest/docs/reference/config/annotations/#SidecarProxyImage) during proxy side car reset analysis

**Comment by manavps** [comment]
Could the tag be pulled from iop.Spec as well? The original issue is about using custom tips images which have a different tag label - https://github.com/kyma-project/istio/pull/664/files#diff-81ee915ad500f8001904f0128068996addf77ca606509f72c656733d7e739358R78

**Comment by videlov** [comment]
@manavps we do not want to provide this option configurable per iop.Spec / configmap or anything else with our official releases. Only option for customisation remains to [build custom image](https://github.com/kyma-project/istio/blob/d91645ab9c8935da03f82ed87623663cf2a621ad/Makefile#L99) yourself changing desired `hub` and `tag` into our [deployment manifests](https://github.com/kyma-project/istio/tree/main/manifests) as single source of truth.

**Comment by manavps** [comment]
@videlov Not asking for it to be configurable, but there needs to be a single source of truth which would be the iop spec you merge in. We do plan to build our custom images, but without that change, the reconciliation fails as the image/tag doesn't match.

**Comment by videlov** [comment]
It will go like this, you have to update `hub` and `tag` in both:
* https://github.com/kyma-project/istio/blob/main/manifests/istio-operator-template.yaml
* https://github.com/kyma-project/istio/blob/main/manifests/istio-operator-template-light.yaml
and build image and deploy with like: 

```bash
export MODULE_VERSION=x.x.x
export IMG_REGISTRY=docker.io/xxx
make module-image
make deploy
```
