### ISSUE TITLE
Library for generating IstioOperator CR

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#7]
**Description**

Implement library that can be used in istio operator controller as well as in istio reconciler. It should accept Istio CR and IstioOperator CR and return IstioOperator CR ready for Istio installation. 

**Reasons**

Modularisation of kyma components

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/15865

**DoD:**

- [x] provide documentation
- [x] provide unit tests
- [x] ~~test on SKR~~
- [x] verify [Get started guides](https://kyma-project.io/docs/kyma/latest/02-get-started/) 
- [x] ~~verify resource limits~~
- [x] followup issue

**Comment by barchw** [comment]
**PR**
- https://github.com/barchw/istio/pull/1
