### ISSUE TITLE
Review and Update Istio-related content in Kyma Learning Journey

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/istio#720]
**Description**

[Delivering Side-by-Side Extensibility based on SAP BTP, Kyma runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime) Kyma Learning Journey got outdated. Markus Haug would like to cooperate with us in updating it.

For the Istio module, we need to take care of the following items:

- [x] [Discovering the Service Mesh](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/discovering-the-service-mesh_d2c0348d-3743-4f71-811f-7975d5f698f6)
- [x] [Discovering Istio](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/discovering-istio_bda31af6-f1dc-4ff8-a5f1-40ce7a2cf837)
- [x]  [Using Istio](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/using-istio_e6d12146-f641-4184-9045-c6ccf5ea4344)

**Reasons**

Content update requiring cross-team collaboration.

**Attachments**

See #5292 in internal /backlog

**Comment by nataliasitko** [comment]
A PR with changes to the learning journey repo has been created
Waiting for the changes to be copied to CMS
