### ISSUE TITLE
Uninstallation of Istio

### ISSUE THREAD

**Issue by strekm** [kyma-project/istio#81]
**Description**

Add support for Istio deletion. When user deletes Istio CR deletion of Istio should be triggered. 

- [x] istio uninstalls on CR deletion
- [x] no leftovers (e.g. CRD, namespace)
- [x] it is possible to install Istio after uninstall

**Reasons**

modularisation

**DoD:**
- [x] provide documentation
- [x] provide unit tests
- [x] test on SKR / gardener
~~- [ ] verify resource limits~~
~~- [ ] followup issue~~
~~- [ ] publish release notes and _What's New_ updates for Kyma customers~~

**PR:**
- [x] https://github.com/kyma-project/istio/pull/90

**Attachments**
part of: https://github.com/kyma-project/istio/issues/38

**Comment by triffer** [comment]
There are a few things to keep in mind as this behavior is currently expected of us.

- When there is a workload in namespace with Istio enabled, this workload won't get the proxy after Istio is installed. This is the same behaviour as when using istioctl.

- When Istio is installed and there is a workload with a proxy then this proxy will stay when Istio is unistalled. This is the same behaviour as when using istioctl.

- Proxy reset will also reset manager on update when the manager is deployed in kyma-system namespace, do we expect this to be an issue. Do we need to exclude the manager from sidecar injection?
