### ISSUE TITLE
Istio performance tests

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/istio#84]
**Description**
Define easily reusable way to monitor and validate istio performance. Default istio deployment should be used (like deployed by kyma deploy) without any modifications which affects default performance. Consider to use already prepared k6 scripts.
Test assumes cluster on production profile. 

**DoD:**
- [x] provide documentation
- [x] provide tests scripts 
- [x] provide provisioning script
- [x] generate report
- [x] followup issue

**Attachments**

- https://linkerd.io/2021/05/27/linkerd-vs-istio-benchmarks/
- https://github.com/istio/istio/wiki/Analyzing-Istio-Performance
- https://blog.mygraphql.com/en/posts/cloud/istio/istio-tunning/istio-thread-balance/

**Comment by werdes72** [comment]
Note about provisioning script: Since the goal is to run those tests in a pipeline, provisioning script focuses only on setting up the k6 environment and running tests. For now we have to create the cluster with Kyma manually. This topic and followup issue will be discussed with PO.
