### ISSUE TITLE
Detect cluster flavour during installation 

### ISSUE THREAD

**Issue by barchw** [kyma-project/istio#95]
**Description**
For support of all cluster types (e.g GKE, k3d, Gardener GCP ...) we need to install istio with specific configuration for the cluster (e.g. CNI configuration). CNI is enabled by default. At the moment we are using k3d IstioOperator file containing CNI configuration for k3d. Implement templating for CNI configuration including gardener, k3d, killercoda cluster options.

ACs:
- [x] istio installs on gardener
- [x] istio installs on k3d
- [x] istio installs on killercoda

**DoD:**
- [x] detect cluster flavour
- [x] install istio with cluster specific configuration
- [x] provide unit tests
- [x] followup issue: https://github.com/kyma-project/kyma/issues/14857

**Attachments**

- Kyma CLI overrides: https://github.com/kyma-project/cli/blob/b13d94142b2b363c9c3592e5b880c316ad11cec6/internal/deploy/values/builder.go
- Kyma CLI cluster identification: https://github.com/kyma-project/cli/blob/3b4ed805c4f94443271a99c394c3a8546a92cf4d/internal/clusterinfo/clusterinfo.go
- #61 

**PR**
- https://github.com/kyma-project/istio/pull/118

**Comment by pbochynski** [comment]
Can you make it configurable?
For example your operator doesn't work with killercoda cluster because of CNI:
```
install Istio CNI is configured as chained plugin, but cannot find existing CNI network config: no networks found in /host/etc/cni/net.d
```
Can I disable CNI somehow?

**Comment by strekm** [comment]
@pbochynski i don't want to expose that configuration to a user. if we turn CNI off it means that workloads need root for proxy-init container. we can think of disabling CNI for k3d / killercoda to simplify setup, resource usage and so on.

**Comment by pbochynski** [comment]
> @pbochynski i don't want to expose that configuration to a user. if we turn CNI off it means that workloads need root for proxy-init container. we can think of disabling CNI for k3d / killercoda to simplify setup, resource usage and so on.

But you need to disable CNI for clusters without CNI plugin or with CNI plugin that doesn't work with istio. So why not make it configurable and if not provided use default (that can be different for different clusters)?

**Comment by TorstenD-SAP** [comment]
I am also not in favor of exposing the CNI config to the user and I think the user should not be able to disable CNI by himself. The usage of CNI is mentioned as a security-related best practice by Istio itself (https://istio.io/latest/docs/ops/best-practices/security/#cni) and the downsides of using the init-container deviate from a lot of best practices to secure Kubernetes at least in a company environment. Kyma should follow and support best practices as much as possible and should make it some kind of convenient for the user to follow them. With modularization, the user will be able to decide to install Istio on his own and with this, he can disable CNI.

**Comment by pbochynski** [comment]
I am ok with not exposing the configuration as long as it will work in clusters without CNI plugin installed.
