### ISSUE TITLE
Include istio-system namespace in the deployment yaml of istio module

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/istio#997]
**Description**

Add `istio-system` to the deployment YAML file (one of release artifacts) in order to have it created and managed by the Kyma Lifecycle Manager.
 
**Reasons**
We need consistent labeling of system resources for all Kyma modules. See: https://github.com/kyma-project/community/issues/922

**DoD:**
- [x] ~~Provide unit and integration tests.~~
- [x] ~~Provide documentation.~~
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] ~~If you changed the resource limits, explain why it was needed.~~
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] ~~Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
- [x] Add release notes.

**Attachments**

**Comment by strekm** [comment]
We need to check if there will be no conflict  between KLM and Istio module.

**Comment by videlov** [comment]
> We need to check if there will be no conflict between KLM and Istio module.

tested both scenarios without any issues, having new module manifest which includes `istio-system` namespace definition:
* creating a new SKR 
* upgrading old SRK

module CR on kcp in both cases in `Ready` state. Double checked few error messages from KLM operator with @ruanxin. All should be good. No issues.

for the tests, I did create a Istio module dev release for it, version 1.9.1
